backend/core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testApp/', include("testApp.urls")),
]

backend/testApp/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = "vapor"
urlpatterns = [
    path("", views.index, name="index"), # Pagina inicial
    # Games #
    path("games/", views.GameView.as_view(), name="create"), # Pagina para postar um jogo
    path("games/", views.GameView.as_view(), name="read"), # Pagina para mostrar os jogos
    path("games/<str:game_id>/", views.GameView.as_view(), name="update"), # Pagina para Atualizar um jogo
    path("games/<str:game_id>/", views.GameView.as_view(), name="delete"), # Pagina para remoover um jogo
    path("games/<str:game_id>/detail", views.GameDetail.as_view(), name="detail"), # Pagina do jogo
    path("games/<str:game_id>/buy", views.GameDetail.as_view(), name="buyGame"), # Compra do jogo
    # Ratings #
    path("games/<str:game_id>/ratings", views.RatingsView.as_view(), name="createRating"), # Postar avaliação de um jogo
    path("games/<str:game_id>/ratings", views.RatingsView.as_view(), name="readRating"), # Ler avaliações de um jogo
    path("ratings/<int:rating_id>", views.RatingsView.as_view(), name="updateRating"), # Atualizar Avaliação
    path("ratings/<int:rating_id>", views.RatingsView.as_view(), name="deleteRating"), # Deletar avaliação
    # Users #
    path("user/", views.UserRegisterView.as_view(), name="createUser"), # Criar usuario
    path("user/authenticate/", views.UserView.as_view(), name="authUser"), # Autenticar usuario
    path("user/<str:id>/", views.UserView.as_view(), name="readUser"), # Ver o perfil de um usuario
    path("user/<str:id>/", views.UserView.as_view(), name="updateUser"), # Atualizar dados de usuario
    path("user/<str:id>/", views.UserView.as_view(), name="deleteUser"), # Deletar usuario
    path("users/", views.GetAllUsers.as_view(), name="allUser"), # Ver todos os usuarios
    path("authenticateduser/", views.AuthenticatedUserView.as_view(), name="readMe"), # Ver dados do usuario autenticado
    # Genres #
    path("genres/", views.GenresViews.as_view(), name="createGenres"), # Criar gênero
    path("genres/", views.GenresViews.as_view(), name="readGenres"), # Ler gênero
    path("genres/<str:id>/", views.GenresViews.as_view(), name="updateGenres"), # Atualizar gênero
    path("genres/<str:id>/", views.GenresViews.as_view(), name="deleteGenres"), # Deletar gênero
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/testApp/models.py
from django.db import models
from datetime import timedelta
from django.utils.timezone import now
from django.contrib.auth.models import AbstractUser

def game_media_path(instance, filename):
    return f"games/{instance.game.id}/media/{filename}"

# Create your models here.
class Genres(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=15)

    def __str__(self):
        return self.name

class Games(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=50)
    price = models.FloatField()
    description = models.TextField()
    isAdults = models.BooleanField()
    genres = models.ManyToManyField(Genres, related_name="genres")
    achievements = models.IntegerField(blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"{self.name} - ${self.price:.2f}"

class User(AbstractUser):
    id = models.BigAutoField(primary_key=True)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)
    about = models.TextField(blank=True)
    level = models.IntegerField(default=0)

    def update_last_login(self):
        self.last_login = now()
        self.save()

    def __str__(self):
        return f"{self.username} - Level: {self.level}"
    
class GameMedia(models.Model):
    GAME_MEDIA_TYPES = [
        ("image", "Image"),
        ("video", "Video"),
    ]

    game = models.ForeignKey(Games, on_delete=models.CASCADE, related_name="media")
    media_type = models.CharField(max_length=10, choices=GAME_MEDIA_TYPES)
    file = models.FileField(upload_to=game_media_path)

class Ratings(models.Model):
    id = models.BigAutoField(primary_key=True)
    value = models.IntegerField()
    body = models.TextField()
    game = models.ForeignKey(Games, on_delete=models.CASCADE, related_name="ratings")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ratings")

    def __str__(self):
        return f"Made by {self.user} - Rate: {self.value}"


class UserGame(models.Model):
    game = models.ForeignKey(Games, on_delete=models.CASCADE, related_name="game_users")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_games")
    achievements = models.IntegerField(default=0)
    last_played = models.DateTimeField(blank=True, null=True)
    time_played = models.DurationField(default=timedelta(0))
    session_start = models.DateTimeField(blank=True, null=True)

    def start_gaming_session(self):
        """Marca o início de uma sessão de jogo"""
        self.session_start = now()
        self.last_played = self.session_start
        self.save()

    def end_gaming_session(self):
        """Finaliza a sessão de jogo e atualiza o tempo total"""
        if self.session_start:
            # Calcula o tempo da sessão atual
            session_duration = now() - self.session_start
            # Adiciona ao tempo total
            self.time_played += session_duration
            # Atualiza last_played e limpa session_start
            self.last_played = now()
            self.session_start = None
            self.save()
            return session_duration
        return None

    def __str__(self):
        return f"{self.user.username} has {self.achievements} achievements for {self.game.name}\nLast Played: {self.last_played}"
    

backend/testApp/forms.py
from django import forms
from .models import *

class GamesForm(forms.ModelForm):
    class Meta:
        model = Games
        fields = '__all__'

        isAdults = forms.ChoiceField(
        choices=[(False, "For Everyone"), (True, "Adults Only")],
        widget=forms.RadioSelect()
        )

        labels = {
            'name' : 'Game Name',
            'price' : 'Price',
            'description' : 'Game Description',
            'isAdults' :  'Is for Adults Only?'
        }

        widgets = {
            'name' : forms.TextInput(attrs={'placeholder': 'The Game'}),
            'price' : forms.NumberInput(attrs={'placeholder': '0,00'}),
            'description' : forms.Textarea(attrs={'placeholder': 'This is a 2D game...'}),
        }

class RatingsForms(forms.ModelForm):
    class Meta:
        model = Ratings
        fields = '__all__'

backend/testApp/views.py
from .serializer import *
from .models import Games
from rest_framework import status
from rest_framework.views import APIView
from django.contrib.auth import authenticate
from rest_framework.response import Response
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from rest_framework.authtoken.models import Token
from rest_framework.exceptions import ValidationError
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import MultiPartParser, FormParser, JSONParser

# Create your views here.
class GameDetail(APIView):
    def post(self, request, game_id): # Compra de jogo
        game = get_object_or_404(Games, id=game_id)
        user = request.user

        if not user.is_authenticated:
            return Response({"error": "User must be authenticated"}, status=status.HTTP_401_UNAUTHORIZED)
            
        if UserGame.objects.filter(user=user, game=game).exists():
            return Response({"message": "You already have this game!"})
            
        UserGame.objects.create(user=user, game=game)
        return Response({"message": "Game purchased!"}, status=status.HTTP_201_CREATED)

    def get(self, request, game_id): # Pagina do jogo
        try:
            game = Games.objects.get(id=game_id)
            serializer = GameSerializer(game)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Games.DoesNotExist:
            return Response({"error": "Game not found"}, status=status.HTTP_404_NOT_FOUND)

class GameView(APIView):
    parser_classes = (MultiPartParser, FormParser, JSONParser)

    def post(self, request):
        serializer = GameSerializer(data=request.data)

        if serializer.is_valid():
            game = serializer.save()

            media_files = request.FILES.getlist('media')
            for file in media_files:
                media_type = "image" if file.content_type.startswith("image") else "video"
                GameMedia.objects.create(game=game, media_type=media_type, file=file)

            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def get(self, request):
        games = Games.objects.all()
        serializer = GameSerializer(games, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
    def put(self, request, game_id):
        try:
            game = Games.objects.get(id=game_id)


            serializer = GameSerializer(game, data=request.data)
            if serializer.is_valid():
                game = serializer.save()

                media_files = request.FILES.getlist('media')
                for file in media_files:
                    media_type = "image" if file.content_type.startswith("image") else "video"
                    GameMedia.objects.create(game=game, media_type=media_type, file=file)
                
                return Response(serializer.data, status=status.HTTP_200_OK)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except Games.DoesNotExist:
            return Response({"error": "Game not found"}, status=status.HTTP_404_NOT_FOUND)
        
    def delete(self, request, game_id, format=None):
        try:
            jogo = Games.objects.get(id=game_id)
            jogo.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        except Games.DoesNotExist:
            return Response({"error": "Game Not Found"}, status=status.HTTP_404_NOT_FOUND)

class RatingsView(APIView):
    def post(self, request, game_id):
        game = get_object_or_404(Games, id=game_id)
        user = request.user

        if not user.is_authenticated:
            return Response({"error": "User must be authenticated"}, status=status.HTTP_401_UNAUTHORIZED)
        
        request.data["game"] = game.id
        request.data["user"] = user.id  

        serializer = RatingSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, game_id):
        ratings = Ratings.objects.filter(game=game_id)
        serializer = RatingSerializer(ratings, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
    def put(self, request, rating_id):
        try:
            rating = Ratings.objects.get(id=rating_id)
            serializer = RatingSerializer(rating, data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_200_OK)
        except:
            return Response({f"error: {serializer.errors}"}, status=status.HTTP_400_BAD_REQUEST)
        
    def delete(self, request, rating_id):
        try:
            rating = Ratings.objects.get(id=rating_id)
            rating.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        except Ratings.DoesNotExist:
            return Response({"error": "Game Not Found"}, status=status.HTTP_404_NOT_FOUND)

class UserRegisterView(APIView):
    def post(self, request):
        username = request.data.get('username')
        password = request.data.get('password')
        password_confirm = request.data.get('password_confirm')

        if password != password_confirm:
            return Response({"error": "The passwords do not match!"}, status=status.HTTP_400_BAD_REQUEST)

        if User.objects.filter(username=username).exists():
            return Response({"error": "The username already exists!"}, status=status.HTTP_400_BAD_REQUEST)

        try:
            User.objects.create_user(username=username, password=password)
            return Response({"message": "Account created successfully!"}, status=status.HTTP_201_CREATED)
        except ValidationError as e:
            return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)

class GetAllUsers(APIView):
    def get(self, request):
        try:
            users = User.objects.all()
            serializer = UserSerializer(users, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except User.DoesNotExist:
            return Response({"error: No registered users!"}, status=status.HTTP_404_NOT_FOUND)     

class UserView(APIView):
    parser_classes = (MultiPartParser, FormParser, JSONParser) # Suporte para arquivos

    def post(self, request):
        username = request.data.get('username')
        password = request.data.get('password')

        user = authenticate(username=username, password=password)

        if user:
            token, created = Token.objects.get_or_create(user=user)
            return Response({"token": token.key}, status=status.HTTP_200_OK)
            # return Response({"message: Login Successful"}, status=status.HTTP_200_OK)
        return Response({"Error: Wrong username or password. Please try again."}, status=status.HTTP_400_BAD_REQUEST)
    
    def get(self, request, id):
        try:
            user = User.objects.get(id=id)
            serializer = UserSerializer(user)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except User.DoesNotExist:
            return Response({"error": "User Not Found"}, status=status.HTTP_404_NOT_FOUND)
        
    def put(self, request, id):
        user = get_object_or_404(User, id=id)
        
        serializer = UserSerializer(user, data=request.data, partial=True)

        if serializer.is_valid():
            if "password" in request.data:
                user.set_password(request.data["password"])
            serializer.save()
            return Response({"message: Account data changed successfully!"}, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, id):
        user = get_object_or_404(User, id=id)
        user.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    
class AuthenticatedUserView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        serializer = UserSerializer(request.user)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
class GenresViews(APIView):
    def post(self, request):
        serializer = GenreSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(status=status.HTTP_200_OK)
        return Response(status=status.HTTP_400_BAD_REQUEST)
    
    def get(self, request):
        genres = Genres.objects.all()
        if not genres:
            return Response(status=status.HTTP_404_NOT_FOUND)
        serializer = GenreSerializer(genres, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
    def put(self, request, id):
        genre = get_object_or_404(Genres, id=id)
        serializer = GenreSerializer(genre, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({"message": "Genre updated successfully"}, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, id):
        genre = get_object_or_404(Genres, id=id)
        genre.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    
def index(request):
    return render(request, "index.html")

backend/testApp/templates/confirmation.html
{% extends 'layout.html' %}

{% block title %}
    <title>Confirmation Page</title>
{% endblock %}

{% block content %}
    <div class="container">
        <form class="jumbotron" method="post">
            {% csrf_token %}
            <h2>Are you sure you want to delete this data? </h2>
            <input type="submit" value="YES" class="btn btn-danger">
            <button class="btn btn-success"><a href="{% url 'vapor:show_url' %}">No</a></button>
        </form>
    </div>
{% endblock %}

backend/testApp/templates/forms.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Add Your Game</h1>
    <div class="form-group">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Publish Game" class="btn btn-success">
        </form>
    </div>
{% endblock %}

backend/testApp/templates/index.html
{% extends "layout.html" %}

{% block title %}
  <title>Home Page</title>
{% endblock %}

{% block content%}
  <h1>Welcome to Vapor!</h1>
  <p>This is the home page, click on one of the links above to be redirected.</p>
{% endblock %}

backend/testApp/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  {% block title %}
  <title>Vapor</title>
  {% endblock %}
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
  <link rel="stylesheet" href="{% static 'vapor/style.css' %}">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbarStyle">
    <a class="navbar-brand" href="#">VAPOR</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'vapor:index' %}">Home Page</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'vapor:create' %}">Upload Game</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'vapor:read' %}">Show Games</a>
        </li>
      </ul>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

backend/testApp/templates/show.html
{% extends "layout.html" %}

{% block title %}
<title>All Games</title>
{% endblock %}

{% block content %}
    <h1>All Games!</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Price</th>
                <th scope="col">Adults</th>
            </tr>
        </thead>
        <tbody>
            {% for i in obj %}
            <tr>
                <td>{{i.name}}</td>
                <td>{{i.description}}</td>
                <td>{{i.price}}</td>
                <td>{{i.isAdults}}</td>
                <td>
                    <button class="btn btn-warning"><a href="{% url 'vapor:update' i.name %}">Update</a></button>&nbsp;&nbsp;
                    <button class="btn btn-danger"><a href="{% url 'vapor:delete' i.name %}">Delete</a></button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

backend/testApp/templates/update.html
{% extends "layout.html" %}

{% block content %}
    <h1>Choose the game you want to update</h1>
{% endblock %}